### ISSUE TITLE
The pre-built binary runs, opens a window, and crashes

### ISSUE THREAD

**Issue by rolfedh** [sveinbjornt/ManDrake#2]
On Mac OS X Sierra.

**Comment by rolfedh** [comment]
I also tried building from source, following the written instructions, but the build in xcode fails. 

ManDrake project Group
Validate Project Settings Group
/Users/rolfedlugy-hegwer/Downloads/ManDrake-master/ManDrake.xcodeproj Update to recommended settings
ManDrake Group
Target Integrity Group
/Users/rolfedlugy-hegwer/Downloads/ManDrake-master/ManDrake.xcodeproj The file “Pods.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/rolfedlugy-hegwer/Downloads/ManDrake-master/Pods/Target Support Files/Pods/Pods.debug.xcconfig)
/Users/rolfedlugy-hegwer/Downloads/ManDrake-master/ManDrake.xcodeproj The file “Pods.release.xcconfig” couldn’t be opened because there is no such file. (/Users/rolfedlugy-hegwer/Downloads/ManDrake-master/Pods/Target Support Files/Pods/Pods.release.xcconfig)
Dependency Analysis Warning Group
The file “Pods.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/rolfedlugy-hegwer/Downloads/ManDrake-master/Pods/Target Support Files/Pods/Pods.debug.xcconfig)
Shell Script Invocation Error Group
diff: /../Podfile.lock: No such file or directory

diff: /Manifest.lock: No such file or directory

error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by sveinbjornt** [comment]
The ACEView editor used in the project seems to be broken in Pods on Sierra. Will take a look and come up with a fix.

**Comment by sveinbjornt** [comment]
This should now build and work, just make sure to update your CocoaPods installation.

**Comment by rolfedh** [comment]
Like this?

```
$ pod install
Analyzing dependencies
[!] The dependency `ACEView` is not used in any concrete target.
The dependency `Sparkle` is not used in any concrete target.

[!] `xcodeproj` was renamed to `project`. Please update your Podfile accordingly.
```

I'm not sure what to do. I downloaded the fresh repo before running pod install...

**Comment by fmeunier** [comment]
Same for me - are you also running the Mac app version of CocoaPods?

**Comment by rolfedh** [comment]
@fmeunier @sveinbjornt Svein, should we create a new issue?

**Comment by zmwangx** [comment]
`Podfile` needs to be updated to post-1.0 format:

```rb
target 'ManDrake'

platform :osx, '10.7'
inhibit_all_warnings!

project 'ManDrake'

pod 'ACEView'
pod 'Sparkle'
```

That said, it still doesn't work for me, even when I try to use the master branch of `ACEView` instead of the old 0.0.5 on CocoaPods:

```rb
pod 'ACEView', :git => 'https://github.com/ACENative/ACEView.git'
```

@sveinbjornt If you were able to build a working artifact, could you please update http://sveinbjorn.org/files/software/mandrake/ManDrake-3.0.zip? Thanks.

**Comment by sveinbjornt** [comment]
Will look into resolving this issue soon.

**Comment by zmwangx** [comment]
Thanks.

**Comment by sveinbjornt** [comment]
OK, a new version of ManDrake which doesn't crash on macOS Sierra is now available for download. Also, source should build just fine.
