### ISSUE TITLE
preview large mdoc

### ISSUE THREAD

**Issue by grylem** [sveinbjornt/ManDrake#4]
texi2mdoc -I/doc wget.texi >wget.mdoc
pod2mdoc big.pod >big.mdoc

open wget.mdoc in ManDrake - no errors in editors, but in preview nothing.
for smallest mdoc - all fine.

tixi2mdoc, pod2mdoc from http://mandoc.bsd.lv/
[wget.mdoc.zip](https://github.com/sveinbjornt/ManDrake/files/2347834/wget.mdoc.zip)

**Comment by sveinbjornt** [comment]
Fixed in master.
