### ISSUE TITLE
cat2html is 32 bit only

### ISSUE THREAD

**Issue by ian-twilightcoder** [sveinbjornt/ManDrake#5]
The cat2html executable should be updated to 64 bit. Or since the source is available maybe it should be built into ManDrake itself?

**Comment by sveinbjornt** [comment]
It's been 64-bit for quite a while. Are you sure you have the latest version?

**Comment by ian-twilightcoder** [comment]
Aha! Check for Updates didn't show me anything but you're right I still had 3.1. Looks great in 3.2!
